name: task3
on:
  push:
    branches:
      - lessons3

jobs:
  python-coin-test:
    runs-on: self-hosted
    needs:
      - install-deps
      - lint
    steps:
      - name: list dir
        run: | 
          pwd
          ls -la

      - name: activate the virtual environment and run the script
        run: |
          source myenv/bin/activate
          ./coincap.py

  install-deps:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Create a virtual environment
        run: python3 -m venv  myvenv
      - name: install dependencies in virtual environment
        run: |
             source myenv/bin/activate
             pip install requests
      
  lint:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: test code
        run: pylint coincap.py
        continue-on-error: true
