name: task3
on:
  push:
    branches:
      - lessons4

jobs:
  python-coin-test:
    runs-on: ubuntu-latest
    needs:
      - install-deps
      - lint
    steps:
      - name: list dir
        run: | 
          pwd
          ls -la

      - name: activate the virtual environment and run the script
        run: |
          source myenv/bin/activate
          ./coincap.py

  install-deps:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Create a virtual environment
        run: python3 -m venv  myvenv
      - name: install dependencies in virtual environment
        run: |
             source myenv/bin/activate
             pip install requests
      
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: test code
        run: pylint coincap.py
        continue-on-error: true

  CD_my_host:
    runs-on: ubuntu-latest
    needs: python-coin-test 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MY_SSH_KEY }}

    - name: Copy files to server
      run: |
        scp -r  ./coincap.py  edgar@192.168.1.113:/cd/test

    - name: Restart server
      run: |
        ssh edgar@192.168.1.113 ./cd/test/coincap.py
