name: task2


on:
  push:
    branches:
      - lessons2

jobs:
  test_task2:
    strategy:
      matrix:
        version: [14,16]
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: instal deps
        run: npm install
      - name: run script
        run: node script.js
