name: task3
on:
  push:
    branches:
      - lessons3

jobs:
  python-coin-test:
    runs-on: self-hosted
    needs:
      - install-deps
      - lint
    steps:
      - name: list dir
        run: | 
          pwd
          ls -la

      - name: run script
        run: python3 script.py

  install-deps:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: install dependencies
        run: pip install requests
      
  lint:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: test code
        run: pylint script.py
        continue-on-error: true
