name: test
env:
  MY_GUTHUB_name : "EdgarHarutyunyan2025"
  MY_GUTHUB_emale: "edgar_harutyunyan_2025@mail.ru"
  MY_GUTHUB_REPO: "task1"
on: 
  push:
    branches: 
      - lessons4
permissions:
  contents: read

jobs:
  my_testing: 
    runs-on: ubuntu-latest
    steps:
      - name: print hello message in testing
        run: echo "hello world from testing job" 
      - name: list
        run: ls -la
      - name: git repo
        run: |
          git config --global user.name ${{ env.MY_GUTHUB_name }}
          git config --global user.email ${{ env.MY_GUTHUB_emale }}
      - name: clone dir my repo
        run: git clone https://github.com/EdgarHarutyunyan2025/$MY_GUTHUB_REPO.git
      - name: cd dir
        run: | 
          cd $MY_GUTHUB_REPO
          echo "hello world" >> text.txt
          ls -la
